version: "2"
linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - paramTypeCombine
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    lll:
      line-length: 140
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
          - lll
          - mnd
        path: _test\.go
      - linters:
          - lll
          - mnd
        path: doc\.go
      - linters:
          - lll
        path: pretty_test_vectors.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  # max-issues-per-linter default is 50.  Set to 0 to disable limit.
  max-issues-per-linter: 0
  # max-same-issues default is 3.  Set to 0 to disable limit.
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - doc\.go
